### ISSUE TITLE
Error: The program can not be opened

### ISSUE THREAD

**Issue by muuvmuuv** [xilopaint/alfred-about-this-mac#1]
This warning shows when pressing ENTER on one entry in the list. Also it takes a bit too long to retrieve and parse. Maybe cache them at some location?

**Comment by xilopaint** [comment]
> This warning shows when pressing ENTER on one entry in the list.

Please, update the workflow to the latest release and the error should be fixed.

> Also it takes a bit too long to retrieve and parse. Maybe cache them at some location?

I don't have plans to cache data since this is not a workflow people are expected to use so frequently.
